### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by Edwin574** [je-boska/react-flow-test#1]
Use react-flow-renderer instead of reactflow.

**Comment by je-boska** [comment]
Hey Edwin! Thanks for this -- however the [react-flow-renderer NPM page](https://www.npmjs.com/package/react-flow-renderer) states that the package was renamed to 'reactflow'. This happened in v11, as stated [in the docs](https://reactflow.dev/docs/guides/migrate-to-v11/).
